client_list/urls.py
from django.urls import path

from client_list.views import Client_list, ClientCreate, ClientUpdate, Client_Detail

app_name = "client"
urlpatterns = [path("clientlist/", Client_list.as_view(), name="client_list"),
               path('client/create', ClientCreate.as_view(), name='client-create'),
               path('client/update/<int:pk>', ClientUpdate.as_view(), name='client-update'),
               path('client/detail/<int:pk>', Client_Detail.as_view(), name="client_detail"),

               ]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from account.views import Register, activate, tracker
from two_factor.admin import AdminSiteOTPRequired
from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),
    path('shop/tracker/', tracker, name='Home'),
    path('account/', include('home.urls')),
    path('comment/', include('comment.urls')),
    path('account/', include("account.urls")),
    path('contact/', include("contact_list.urls")),
    path('', include(tf_twilio_urls)),
    path('client_list/', include("client_list.urls")),
    path('reference_list/', include("reference_list.urls")),
    path('shipment_list/', include("shipment_list.urls")),
    path('invoice/', include('invoice.urls')),
    path('mail/', include('mailbox2.urls')),
    path('todo/', include('todo.urls', namespace="todo")),
    path('calendar/', include('calendar_event.urls', namespace='calendar')),
    path('', include(tf_urls)),
    path('register/', Register.as_view(), name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('summernote/', include('django_summernote.urls')),
    path('tinymce/', include('tinymce.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home.views import Index

urlpatterns = [
    path('', Index, name='home')
]

invoice/urls.py
from django.urls import path

from . import views

app_name = "invoice"
urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('invoices', views.invoices, name='invoices'),
    path('products', views.products, name='products'),
    path('product/delete/<slug:slug>', views.deleteproduct, name='delete-product'),
    path('invoices/create', views.createInvoice, name='create-invoice'),
    path('invoices/create-build/<slug:slug>', views.createBuildInvoice, name='create-build-invoice'),
    path('invoices/delete/<slug:slug>', views.deleteInvoice, name='delete-invoice'),
    path('company/settings', views.companySettings, name='company-settings'),
    path('invoices/view-pdf/<slug:slug>', views.viewPDFInvoice, name='view-pdf-invoice'),
    path('invoices/view-document/<slug:slug>', views.viewDocumentInvoice, name='view-document-invoice'),
    path('invoices/email-document/<slug:slug>', views.emailDocumentInvoice, name='email-document-invoice'),
    #     demurrage

    path('demo-invoices', views.demurrage_invoices, name='demo-invoices'),
    path('container/delete/<slug:slug>', views.deletecontainer, name='delete-container'),
    path('demo-invoices/create', views.createDemoInvoice, name='create-demo-invoice'),
    path('demo-invoices/create-build/<slug:slug>', views.createBuildDemoInvoice, name='create-build-demo-invoice'),
    path('demo-invoices/delete/<slug:slug>', views.deleteDemoInvoice, name='delete-demo-invoice'),
    path('demo-invoices/view-pdf/<slug:slug>', views.viewPDFDemoInvoice, name='view-pdf-demo-invoice'),
    path('demo-invoices/view-document/<slug:slug>', views.viewDocumentDemoInvoice, name='view-document-demo-invoice'),
    path('demo-invoices/email-document/<slug:slug>', views.emailDocumentDemoInvoice,
         name='email-document-demo-invoice'),
]

invoice/views.py
import os
from functools import wraps
from uuid import uuid4

import pdfkit as pdfkit
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import get_template
from djmoney.money import Money

from client_list.models import ClientList, Settings
from config import settings
from invoice.filters import DemurrageFilter, InquiryFilter
from invoice.forms import ProductForm, InvoiceForm, ClientSelectForm, ShipmentSelectForm, ContainerForm, DumarrageForm
from invoice.functions import emailInvoiceClient
from invoice.models import Invoice, Product, Demurrage, Container


def login_required(f):
    @wraps(f)
    def g(request, *args, **kwargs):
        if request.user.is_sales or request.user.is_superuser:
            return f(request, *args, **kwargs)
        else:
            return render(request, "registration/home.html")

    return g


@login_required
def dashboard(request):
    clients = ClientList.objects.filter(sales=request.user).count()
    inquiries = Invoice.objects.filter(client__sales=request.user).count()
    ConfirmInquiry = Invoice.objects.filter(client__sales=request.user, status='CONFIRM').count()
    Demurrage_invoices = Demurrage.objects.filter(shipment=True).count()
    Demo_F_invoices = Demurrage.objects.filter(shipment=True, demo_F=True).count()

    context = {}
    context['clients'] = clients
    context['inquiries'] = inquiries
    context['ConfirmInquiry'] = ConfirmInquiry
    context['Demurrage_invoices'] = Demurrage_invoices
    context['Demo_F_invoices'] = Demo_F_invoices
    return render(request, 'invoice/dashboard.html', context)


@login_required
def invoices(request):
    context = {}
    if request.user.is_superuser:
        invoices_filter = InquiryFilter(request.GET, queryset=Invoice.objects.filter(client=True))

    else:
        invoices_filter = InquiryFilter(request.GET,
                                        queryset=Invoice.objects.filter(client=True, client__sales=request.user))

    context['filter'] = invoices_filter

    return render(request, 'invoice/invoices.html', context)


@login_required
def products(request):
    context = {}
    products = Product.objects.filter(invoice__client__sales=request.user)
    context['products'] = products

    return render(request, 'invoice/products.html', context)


@login_required
def createInvoice(request):
    # create a blank invoice ....
    number = 'INV-' + str(uuid4()).split('-')[1]
    newInvoice = Invoice.objects.create(number=number)
    newInvoice.save()

    inv = Invoice.objects.get(number=number)
    return redirect('invoice:create-build-invoice', slug=inv.slug)


def createBuildInvoice(request, slug):
    # fetch that invoice
    try:
        invoice = Invoice.objects.get(slug=slug)
        pass
    except:
        messages.error(request, 'Something went wrong')
        return redirect('invoice:invoices')

    # fetch all the products - related to this invoice
    products = Product.objects.filter(invoice=invoice)

    context = {}
    context['invoice'] = invoice
    context['products'] = products

    if request.method == 'GET':
        prod_form = ProductForm()
        inv_form = InvoiceForm(instance=invoice)
        client_form = ClientSelectForm(user=request.user)
        context['prod_form'] = prod_form
        context['inv_form'] = inv_form
        context['client_form'] = client_form
        return render(request, 'invoice/create-invoice.html', context)

    if request.method == 'POST':
        prod_form = ProductForm(request.POST)
        inv_form = InvoiceForm(request.POST, instance=invoice)
        client_form = ClientSelectForm(request.POST, user=request.user, instance=invoice)

        if prod_form.is_valid():
            obj = prod_form.save(commit=False)
            obj.invoice = invoice
            obj.save()

            messages.success(request, "Invoice product added succesfully")
            return redirect('invoice:create-build-invoice', slug=slug)
        elif inv_form.is_valid and 'paymentTerms' in request.POST:
            inv_form.save()

            messages.success(request, "Invoice updated succesfully")
            return redirect('invoice:create-build-invoice', slug=slug)
        elif client_form.is_valid() and 'client' in request.POST:

            client_form.save()
            messages.success(request, "Client added to invoice succesfully")
            return redirect('invoice:create-build-invoice', slug=slug)
        else:
            context['prod_form'] = prod_form
            context['inv_form'] = inv_form
            context['client_form'] = client_form
            messages.error(request, "Problem processing your request")
            return render(request, 'invoice/create-invoice.html', context)

    return render(request, 'invoice/create-invoice.html', context)


def deleteInvoice(request, slug):
    try:
        Invoice.objects.get(slug=slug).delete()
    except:
        messages.error(request, 'Something went wrong')
        return redirect('invoice:invoices')

    return redirect('invoice:invoices')


def deleteproduct(request, slug):
    try:
        prod = Product.objects.get(slug=slug)
        invoice_slug = prod.invoice.slug
        Product.objects.get(slug=slug).delete()
    except:
        prod = Product.objects.get(slug=slug)
        invoice_slug = prod.invoice.slug
        messages.error(request, 'Something went wrong')
        return redirect('invoice:create-build-invoice', slug=invoice_slug)
    messages.success(request, "The selected product was removed.")
    return redirect('invoice:create-build-invoice', slug=invoice_slug)


def companySettings(request):
    company = Settings.objects.filter(sales=request.user)
    context = {'company': company}
    return render(request, 'invoice/company-settings.html', context)


def viewPDFInvoice(request, slug):
    # fetch that invoice
    try:
        invoice = Invoice.objects.get(slug=slug)
        pass
    except:
        messages.error(request, 'Something went wrong')
        return redirect('invoice:invoices')

    # fetch all the products - related to this invoice
    products = Product.objects.filter(invoice=invoice)

    # Get Client Settings
    p_settings = Settings.objects.filter(sales=request.user)

    # Calculate the Invoice Total
    invoiceCurrency = ''
    invoiceTotal = 0.0

    if len(products) > 0:
        for x in products:
            y = (x.quantity) * (x.currency)
            invoiceTotal += y
    else:
        invoiceTotal = ''

    context = {}
    context['invoice'] = invoice
    context['products'] = products
    context['p_settings'] = p_settings
    context['invoiceTotal'] = invoiceTotal

    return render(request, 'invoice/invoice-template.html', context)


def viewDocumentInvoice(request, slug):
    # fetch that invoice
    try:
        invoice = Invoice.objects.get(slug=slug)
        pass
    except:
        messages.error(request, 'Something went wrong')
        return redirect('invoice:invoices')

    # fetch all the products - related to this invoice
    products = Product.objects.filter(invoice=invoice)

    # Get Client Settings
    p_settings = Settings.objects.filter(sales=request.user)

    # Calculate the Invoice Total
    invoiceCurrency = ''
    invoiceTotal = 0.0

    if len(products) > 0:
        for x in products:
            y = (x.quantity) * (x.currency)
            invoiceTotal += y
    else:
        invoiceTotal = ''

    context = {}
    context['invoice'] = invoice
    context['products'] = products
    context['p_settings'] = p_settings
    context['invoiceTotal'] = invoiceTotal

    # The name of your PDF file
    filename = '{}.pdf'.format(invoice.uniqueId)

    # HTML FIle to be converted to PDF - inside your Django directory
    template = get_template('invoice/pdf-template.html')

    # Render the HTML
    html = template.render(context)

    # Options - Very Important [Don't forget this]
    options = {
        'encoding': 'UTF-8',
        'javascript-delay': '1',  # Optional
        'enable-local-file-access': None,  # To be able to access CSS
        'page-size': 'A4',
        'custom-header': [
            ('Accept-Encoding', 'gzip')
        ],
    }
    # Javascript delay is optional

    # Remember that location to wkhtmltopdf
    config_path = 'C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=config_path)

    # IF you have CSS to add to template
    css1 = os.path.join(settings.CSS_LOCATION, 'assets', 'css', 'bootstrap.min.css')
    css2 = os.path.join(settings.CSS_LOCATION, 'assets', 'css', 'dashboard.css')

    # Create the file
    file_content = pdfkit.from_string(html, False, configuration=config, options=options)

    # Create the HTTP Response
    response = HttpResponse(file_content, content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filename = {}'.format(filename)

    # Return
    return response


def emailDocumentInvoice(request, slug):
    # fetch that invoice
    try:
        invoice = Invoice.objects.get(slug=slug)
        pass
    except:
        messages.error(request, 'Something went wrong')
        return redirect('invoice:invoices')

    # fetch all the products - related to this invoice
    products = Product.objects.filter(invoice=invoice)

    # Get Client Settings
    p_settings = Settings.objects.filter(sales=request.user)

    # Calculate the Invoice Total
    invoiceTotal = 0.0
    if len(products) > 0:
        for x in products:
            y = (x.quantity) * (x.currency)
            invoiceTotal += y
    else:
        invoiceTotal = ''

    context = {}
    context['invoice'] = invoice
    context['products'] = products
    context['p_settings'] = p_settings
    context['invoiceTotal'] = invoiceTotal

    # The name of your PDF file
    filename = '{}.pdf'.format(invoice.uniqueId)

    # HTML FIle to be converted to PDF - inside your Django directory

templates/invoice/company-settings.html
{% extends 'partials/base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block main %}


  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Company Settings</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group me-2">
        
      </div>
    </div>
  </div>


  <div class="container">
    <div class="card">
      <div class="card-body">

        <div class="row">
          <div class="col-lg-6">
            <h5 style="font-size: large" class="card-title">Company Name: {{company.0.companyName}}</h5>
            <hr>
            <p class="card-text"><strong>Address:</strong> {{company.0.addressLine}}</p>
            <p class="card-text"><strong>Postal Code:</strong> {{company.0.postalCode}}</p>
            <p class="card-text"><strong>national_id:</strong> {{company.0.national_id}}</p>
            <br>
            <p class="card-text"><strong>Phone Number:</strong> {{company.0.sales.phone_number}}</p>
            <p class="card-text"><strong>Email:</strong> {{company.0.sales.email}}</p>
            <br>
          </div>


          <div class="col-lg-5">
            <div class="p-5">
            <img class=img-fluid  src="{% static 'invoice/assets/img/empty.svg' %}" alt="Skolo Online Learning">
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>


{% endblock %}

templates/invoice/create-demo-invoice.html
{% extends 'partials/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block css %}
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}




{% block main %}



    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Create an Invoice</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{% url 'invoice:demo-invoices' %}">
                    <button type="button" class="btn btn-primary">Go Back</button>
                </a>
            </div>
        </div>
    </div>



    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                Huyar Tarabar Online Demurrage Invoice Generator
            </div>

            <div class="card-body">

                <div class="row">
                    <div class="col-lg-12">
                        <h5 class="card-title">Add CONTAINER to your invoice
                            <button href="#addProductModal" type="button" class="btn btn-link" data-bs-toggle="modal">
                                ADD CONTAINER
                            </button>
                        </h5>

                        {% if containers|length > 0 %}
                            <div class="table-responsive">
                                <table class="table table-striped table-sm">
                                    <thead>
                                    <tr>

                                        <th>container_number</th>
                                        <th>size</th>
                                        <th>discharge_time</th>
                                        <th>return_time</th>
                                        <th>free_time Invoice</th>
                                        <th>Demurrage_amount</th>
                                        <th>damage_amount</th>
                                        <th>delete</th>

                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for container in containers %}
                                        <tr>
                                            <td>{{ container.container_number }}</td>
                                            <td>{{ container.size }}</td>
                                            <td>{{ container.discharge_time }}</td>
                                            <td>{{ container.return_time }} {{ container.price }}</td>
                                            <td>{{ container.free_time }}</td>
                                            <td>{{ container.Demurrage_amount }}</td>
                                            <td>{{ container.damage_amount }}</td>
                                            <td>
                                                <a href="{% url 'invoice:delete-container' container.slug %}">
                                                    <button class="btn btn-danger"> DELETE</button>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        {% endif %}
                    </div>
                </div>

                <br>


                <div class="row">
                    <div class="col-lg-6">

                        <form class="" action="#" method="post">

                            {% csrf_token %}
                            {% crispy demo_inv_form %}

                        </form>

                    </div>
                    <div class="col-lg-6">
                        <h5 class="card-title"> Select Client to Add </h5>
                        <br>
                        <h5 class="card-title"> Current Client: <span
                                class="badge bg-success">{{ demo_invoice.shipment.shipment_number }}</span></h5>
                        <br>

                        <div class="mb-5">
                            <form class="" action="#" method="post">
                                {% csrf_token %}

                                {{ shipment_form|crispy }}

                                <button type="submit" class="btn btn-primary">ADD shipment</button>
                            </form>
                        </div>


                        <div class="row">
                            <div class="col-lg-4">
                                <a href="{% url 'invoice:view-pdf-demo-invoice' demo_invoice.slug %}">
                                    <button class="btn btn-info text-white"> VIEW DEMURRAGE INVOICE</button>
                                </a>
                            </div>
                            <div class="col-lg-4">
                                <a href="{% url 'invoice:view-document-demo-invoice' demo_invoice.slug %}">
                                    <button class="btn btn-success text-white"> VIEW PDF DEMURRAGE INVOICE</button>
                                </a>
                            </div>
                            <div class="col-lg-4">
                                <a href="{% url 'invoice:email-document-demo-invoice' demo_invoice.slug %}">
                                    <button class="btn btn-warning text-white"> EMAIL DEMURRAGE INVOICE</button>
                                </a>
                            </div>
                        </div>


                    </div>
                </div>


            </div>
        </div>
    </div>





    <!-- MODALS MODALS -->
    <!-- Modals Start Here -->
    <div class="modal modal-sheet py-5" tabindex="-1" id="addProductModal">
        <div class="modal-dialog">
            <div class="modal-content rounded-6 shadow">

                <form class="" action="#" method="post" enctype="multipart/form-data">
                    {% csrf_token %}


                    <div class="modal-header border-bottom-0">
                        <h5 class="modal-title">Add Invoice Container</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body py-0">


                        {{ container_form.as_p }}


                    </div>
                    <div class="modal-footer flex-column border-top-0">
                        <button type="submit" class="btn btn-lg btn-primary w-100 mx-0 mb-2">Save changes</button>
                    </div>

                </form>
            </div>
        </div>
    </div>



{% endblock %}

templates/invoice/create-invoice.html
{% extends 'partials/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block css %}
    <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}




{% block main %}



    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Create an Invoice</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <a href="{% url 'invoice:invoices' %}">
                    <button type="button" class="btn btn-primary">Go Back</button>
                </a>
            </div>
        </div>
    </div>



    <div class="container-fluid">
        <div class="card">
            <div class="card-header">
                Skolo Online Invoice Generator
            </div>

            <div class="card-body">

                <div class="row">
                    <div class="col-lg-12">
                        <h5 class="card-title">Add Products to your invoice
                            <button href="#addProductModal" type="button" class="btn btn-link" data-bs-toggle="modal">
                                ADD PRODUCT
                            </button>
                        </h5>

                        {% if products|length > 0 %}
                            <div class="table-responsive">
                                <table class="table table-striped table-sm">
                                    <thead>
                                    <tr>

                                        <th>Title</th>
                                        <th>Description</th>
                                        <th>Quantity</th>
                                        <th>Price</th>
                                        <th>Related Invoice</th>
                                        <th>delete</th>

                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for product in products %}
                                        <tr>
                                            <td>{{ product.title }}</td>
                                            <td>{{ product.description }}</td>
                                            <td>{{ product.quantity }}</td>
                                            <td>{{ product.currency }} {{ product.price }}</td>
                                            <td>{{ product.invoice.number }}</td>
                                            <td>
                                                <a href="{% url 'invoice:delete-product' product.slug %}">
                                                    <button class="btn btn-danger"> DELETE</button>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                            </div>
                        {% endif %}
                    </div>
                </div>

                <br>


                <div class="row">
                    <div class="col-lg-6">

                        <form class="" action="#" method="post">

                            {% csrf_token %}
                            {% crispy inv_form %}

                        </form>

                    </div>
                    <div class="col-lg-6">
                        <h5 class="card-title"> Select Client to Add </h5>
                        <br>
                        <h5 class="card-title"> Current Client: <span
                                class="badge bg-success">{{ invoice.client.companyName }}</span></h5>
                        <br>

                        <div class="mb-5">
                            <form class="" action="#" method="post">
                                {% csrf_token %}

                                {{ client_form|crispy }}

                                <button type="submit" class="btn btn-primary">ADD CLIENT</button>
                            </form>
                        </div>


                        <div class="row">
                            <div class="col-lg-4">
                                <a href="{% url 'invoice:view-pdf-invoice' invoice.slug %}">
                                    <button class="btn btn-info text-white"> VIEW CLIENT INVOICE</button>
                                </a>
                            </div>
                            <div class="col-lg-4">
                                <a href="{% url 'invoice:view-document-invoice' invoice.slug %}">
                                    <button class="btn btn-success text-white"> VIEW PDF INVOICE</button>
                                </a>
                            </div>
                            <div class="col-lg-4">
                                <a href="{% url 'invoice:email-document-invoice' invoice.slug %}">
                                    <button class="btn btn-warning text-white"> EMAIL CLIENT INVOICE</button>
                                </a>
                            </div>
                        </div>


                    </div>
                </div>


            </div>
        </div>
    </div>





    <!-- MODALS MODALS -->
    <!-- Modals Start Here -->
    <div class="modal modal-sheet py-5" tabindex="-1" id="addProductModal">
        <div class="modal-dialog">
            <div class="modal-content rounded-6 shadow">

                <form class="" action="#" method="post" enctype="multipart/form-data">
                    {% csrf_token %}


                    <div class="modal-header border-bottom-0">
                        <h5 class="modal-title">Add Invoice Product</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>

                    <div class="modal-body py-0">


                        {{ prod_form.as_p }}


                    </div>
                    <div class="modal-footer flex-column border-top-0">
                        <button type="submit" class="btn btn-lg btn-primary w-100 mx-0 mb-2">Save changes</button>
                    </div>

                </form>
            </div>
        </div>
    </div>



{% endblock %}

templates/invoice/dashboard.html
{% extends 'partials/base.html' %}

{% load static %}
{% load crispy_forms_tags %}


{% block main %}


    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">

            </div>
        </div>
    </div>


    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-lg-12">

                        <div class="card mb-5">
                            <h5 class="card-header">inquiries</h5>
                            <div class="card-body">
                                <h5 class="card-title">Total Number of inquiries: {{ inquiries }}</h5>
                                <h5 class="card-title"> Inquiries Confirmed: {{ ConfirmInquiry }}</h5>
                                <a href="{% url 'invoice:invoices' %}" class="btn btn-primary btn-lg">View inquiries</a>
                            </div>
                        </div>
                        <div class="card mb-5">
                            <h5 class="card-header">Demurrage Invoices</h5>
                            <div class="card-body">
                                <h5 class="card-title">Total Number of Demurrage Invoices: {{ Demurrage_invoices }}</h5>
                                <h5 class="card-title">Total Number of Demurrage Final
                                    Invoices: {{ Demo_F_invoices }}</h5>
                                <a href="{% url 'invoice:demo-invoices' %}" class="btn btn-primary btn-lg">View
                                    Demurrage Invoices</a>
                            </div>
                        </div>
                        <div class="card mb-5">
                            <h5 class="card-header">Clients</h5>
                            <div class="card-body">
                                <h5 class="card-title">Total Number of Clients: {{ clients }}</h5>
                                <a href="{% url 'client:client_list' %}" class="btn btn-primary btn-lg">View Clients</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-lg-6">
                <div class="p-5">
                    <img class=img-fluid src="{% static 'invoice/assets/img/empty.svg' %}" alt="Skolo Online Learning">
                </div>
            </div>
        </div>
    </div>




{% endblock %}