account/urls.py
from django.urls import path

from account.views import GoogleMap, Home, MapVector, Profile, ProfileDetailView

app_name = "account"
urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('map-google', GoogleMap.as_view(), name="google_map"),
    path('vector-map', MapVector.as_view(), name="vector_map"),
    path('profile/edit', Profile.as_view(), name='profile'),
    path('profile/detail/<int:pk>', ProfileDetailView.as_view(), name="profile_detail"),
]

comment/api/urls.py
from django.urls import path, re_path
from rest_framework.urlpatterns import format_suffix_patterns

from comment.api import views

app_name = 'comment-api'

urlpatterns = [
    path('comments/', views.CommentList.as_view(), name='list'),
    path('comments/create/', views.CommentCreate.as_view(), name='create'),
    path('comments/<int:pk>/', views.CommentDetail.as_view(), name='detail'),
    path('comments/<int:pk>/react/<str:reaction>/', views.CommentDetailForReaction.as_view(), name='react'),
    path('comments/<int:pk>/flag/', views.CommentDetailForFlag.as_view(), name='flag'),
    path(
        'comments/<int:pk>/flag/state/change/',
        views.CommentDetailForFlagStateChange.as_view(),
        name='flag-state-change'
    ),
    re_path(r'^comments/confirm/(?P<key>[^/]+)/$', views.ConfirmComment.as_view(), name='confirm-comment'),
    path('comments/toggle-subscription/', views.ToggleFollowAPI.as_view(), name='toggle-subscription'),
    path('comments/subscribers/', views.SubscribersAPI.as_view(), name='subscribers'),
    path('comments/toggle-blocking/', views.ToggleBlockingAPI.as_view(), name='toggle-blocking'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

comment/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog

from comment import __version__
from comment.views import (
    CreateComment, UpdateComment, DeleteComment, SetReaction, SetFlag, ChangeFlagState,
    ConfirmComment, ToggleFollowView, ToggleBlockingView
)

app_name = 'comment'


urlpatterns = [
    path('create/', CreateComment.as_view(), name='create'),
    path('edit/<int:pk>/', UpdateComment.as_view(), name='edit'),
    path('delete/<int:pk>/', DeleteComment.as_view(), name='delete'),
    path('<int:pk>/react/<str:reaction>/', SetReaction.as_view(), name='react'),
    path('<int:pk>/flag/', SetFlag.as_view(), name='flag'),
    path('<int:pk>/flag/state/change/', ChangeFlagState.as_view(), name='flag-change-state'),
    re_path(r'^confirm/(?P<key>[^/]+)/$', ConfirmComment.as_view(), name='confirm-comment'),
    path('toggle-subscription/', ToggleFollowView.as_view(), name='toggle-subscription'),
    path('toggle-blocking/', ToggleBlockingView.as_view(), name='toggle-blocking'),
    # javascript translations
    # The value returned by _get_version() must change when translations change.
    path(
        'jsi18n/',
        cache_page(86400, key_prefix='js18n-%s' % __version__)(JavaScriptCatalog.as_view()),
        name='javascript-catalog'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from account.views import Register, activate, tracker
from two_factor.admin import AdminSiteOTPRequired
from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),
    path('shop/tracker/', tracker, name='Home'),
    path('account/', include('home.urls')),
    path('comment/', include('comment.urls')),
    path('account/', include("account.urls")),
    path('contact/', include("contact_list.urls")),
    path('', include(tf_twilio_urls)),
    path('client_list/', include("client_list.urls")),
    path('reference_list/', include("reference_list.urls")),
    path('shipment_list/', include("shipment_list.urls")),
    path('invoice/', include('invoice.urls')),
    path('mail/', include('mailbox2.urls')),
    path('todo/', include('todo.urls', namespace="todo")),
    path('calendar/', include('calendar_event.urls', namespace='calendar')),
    path('', include(tf_urls)),
    path('register/', Register.as_view(), name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('summernote/', include('django_summernote.urls')),
    path('tinymce/', include('tinymce.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home.views import Index

urlpatterns = [
    path('', Index, name='home')
]

comment/api/views.py
from django.core.exceptions import ValidationError
from rest_framework import generics, permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from comment.validators import ValidatorMixin, ContentTypeValidator
from comment.api.serializers import CommentSerializer, CommentCreateSerializer
from comment.api.permissions import (
    IsOwnerOrReadOnly, FlagEnabledPermission, CanChangeFlaggedCommentState, SubscriptionEnabled,
    CanGetSubscribers, CanCreatePermission, UserPermittedOrReadOnly, CanBlockUsers
)
from comment.models import Comment, Reaction, ReactionInstance, Flag, FlagInstance, Follower
from comment.utils import get_comment_from_key, CommentFailReason
from comment.messages import FlagError, EmailError
from comment.views import BaseToggleFollowView, CommentCreateMixin, BaseToggleBlockingView


class CommentCreate(ValidatorMixin, generics.CreateAPIView):
    serializer_class = CommentCreateSerializer
    permission_classes = (CanCreatePermission, UserPermittedOrReadOnly)
    api = True

    def get_serializer_context(self):
        self.validate(self.request)
        context = super().get_serializer_context()
        context['model_obj'] = self.model_obj
        context['parent_comment'] = self.parent_comment
        context['email'] = self.request.GET.get('email', None)
        return context


class CommentList(ContentTypeValidator, generics.ListAPIView):
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)
    api = True

    def get_queryset(self):
        self.validate(self.request)
        return Comment.objects.filter_parents_by_object(self.model_obj).select_related('user', 'reaction', 'flag')


class CommentDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Comment.objects.all().select_related('user', 'reaction', 'flag')
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly, UserPermittedOrReadOnly)


class CommentDetailForReaction(generics.UpdateAPIView):
    queryset = Comment.objects.all().select_related('user', 'reaction', 'flag')
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, UserPermittedOrReadOnly)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['reaction_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        reaction_type = kwargs.get('reaction', None)
        reaction_obj = Reaction.objects.get_reaction_object(comment)
        try:
            ReactionInstance.objects.set_reaction(
                user=request.user,
                reaction=reaction_obj,
                reaction_type=reaction_type
            )
        except ValidationError as e:
            return Response({'detail': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        comment.reaction.refresh_from_db()
        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class CommentDetailForFlag(generics.UpdateAPIView):
    queryset = Comment.objects.all().select_related('user', 'reaction', 'flag')
    serializer_class = CommentSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, FlagEnabledPermission, UserPermittedOrReadOnly)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['flag_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        flag = Flag.objects.get_for_comment(comment)
        reason = request.data.get('reason') or request.POST.get('reason')
        info = request.data.get('info') or request.POST.get('info')
        try:
            FlagInstance.objects.set_flag(request.user, flag, reason=reason, info=info)
        except ValidationError as e:
            return Response({'detail': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class CommentDetailForFlagStateChange(generics.UpdateAPIView):
    queryset = Comment.objects.all().select_related('user', 'reaction', 'flag')
    serializer_class = CommentSerializer
    permission_classes = (CanChangeFlaggedCommentState, UserPermittedOrReadOnly)

    def get_serializer_context(self):
        context = super().get_serializer_context()
        context['flag_update'] = True
        return context

    def post(self, request, *args, **kwargs):
        comment = self.get_object()
        flag = Flag.objects.get_for_comment(comment)
        state = request.data.get('state') or request.POST.get('state')
        try:
            state = flag.get_clean_state(state)
            if not comment.is_edited and state == flag.RESOLVED:
                return Response(
                    {'detail': FlagError.RESOLVE_UNEDITED_COMMENT},
                    status=status.HTTP_400_BAD_REQUEST
                )
            flag.toggle_state(state, request.user)
        except ValidationError as e:
            return Response({'detail': e.messages}, status=status.HTTP_400_BAD_REQUEST)

        serializer = self.get_serializer(comment)
        return Response(serializer.data, status=status.HTTP_200_OK)


class ConfirmComment(APIView, CommentCreateMixin):
    def get(self, request, *args, **kwargs):
        key = kwargs.get('key', None)
        temp_comment = get_comment_from_key(key)

        if temp_comment.why_invalid == CommentFailReason.BAD:
            return Response({'detail': EmailError.BROKEN_VERIFICATION_LINK}, status=status.HTTP_400_BAD_REQUEST)

        if temp_comment.why_invalid == CommentFailReason.EXISTS:
            return Response({'detail': EmailError.USED_VERIFICATION_LINK}, status=status.HTTP_200_OK)

        comment = self.perform_save(temp_comment.obj, request)

        return Response(CommentSerializer(comment).data, status=status.HTTP_201_CREATED)


class ToggleFollowAPI(BaseToggleFollowView, APIView):
    api = True
    response_class = Response
    permission_classes = (SubscriptionEnabled, permissions.IsAuthenticated, UserPermittedOrReadOnly)

    def post(self, request, *args, **kwargs):
        self.validate(request)
        return super().post(request, *args, **kwargs)


class SubscribersAPI(ContentTypeValidator, APIView):
    api = True
    permission_classes = (CanGetSubscribers,)

    def get(self, request, *args, **kwargs):
        self.validate(request)
        return Response({
            'app_name': self.model_obj._meta.app_label,
            'model_name': self.model_obj.__class__.__name__,
            'model_id': self.model_obj.id,
            'followers': Follower.objects.get_emails_for_model_object(self.model_obj)
        })


class ToggleBlockingAPI(BaseToggleBlockingView, APIView):
    permission_classes = (CanBlockUsers,)
    response_class = Response

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

comment/views/blocker.py
from django.views import View

from comment.models import BlockedUser, BlockedUserHistory, Comment
from comment.mixins import CanBlockUsersMixin
from comment.responses import UTF8JsonResponse, DABResponseData
from comment.messages import BlockUserError


class BaseToggleBlockingView(DABResponseData):
    response_class = None

    def get_response_class(self):
        assert self.response_class is not None, (
                "'%s' should either include a `response_class` attribute, "
                "or override the `get_response_class()` method."
                % self.__class__.__name__
        )
        return self.response_class

    def post(self, request, *args, **kwargs):
        response_class = self.get_response_class()
        request_data = request.POST or getattr(request, 'data', {})
        comment_id = request_data.get('comment_id', None)
        try:
            comment = Comment.objects.get(id=int(comment_id))
        except (Comment.DoesNotExist, ValueError, TypeError):
            self.error = {
                'detail': BlockUserError.INVALID
            }
            self.status = 400
            return response_class(self.json(), status=self.status)

        blocked_user, created = BlockedUser.objects.get_or_create_blocked_user_for_comment(comment)

        if not created:
            blocked_user.blocked = not blocked_user.blocked
        blocked_user.save()

        reason = request_data.get('reason', None)
        if blocked_user.blocked and not reason:
            reason = comment.content

        BlockedUserHistory.objects.create_history(
            blocked_user=blocked_user,
            blocker=request.user,
            reason=reason
        )
        self.data = {
            'blocked_user': comment.get_username(),
            'blocked': blocked_user.blocked,
            'urlhash': comment.urlhash
        }
        return response_class(self.json())


class ToggleBlockingView(CanBlockUsersMixin, BaseToggleBlockingView, View):
    response_class = UTF8JsonResponse

comment/views/reactions.py
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.http import require_POST

from comment.mixins import BaseCommentMixin
from comment.models import Comment, Reaction, ReactionInstance
from comment.responses import UTF8JsonResponse, DABResponseData
from comment.messages import ReactionInfo


@method_decorator(require_POST, name='dispatch')
class SetReaction(BaseCommentMixin, View, DABResponseData):
    def post(self, request, *args, **kwargs):
        comment = get_object_or_404(
            Comment.objects.select_related('user', 'reaction', 'flag'),
            pk=self.kwargs.get('pk')
        )
        reaction_type = kwargs.get('reaction', None)
        reaction_obj = Reaction.objects.get_reaction_object(comment)
        try:
            ReactionInstance.objects.set_reaction(user=request.user, reaction=reaction_obj, reaction_type=reaction_type)
        except ValidationError as e:
            self.error = e.message
            self.status = 400
            return UTF8JsonResponse(self.json(), status=self.status)

        comment.reaction.refresh_from_db()
        self.data = {
            'status': 0,
            'likes': comment.likes,
            'dislikes': comment.dislikes,
        }
        self.msg = ReactionInfo.UPDATED_SUCCESS
        return UTF8JsonResponse(self.json())

comment/templates/comment/comments/apply_icon.html
<button class="{% block apply_btn_cls %}btn btn-link{% endblock apply_btn_cls %}" type="submit" name="form_type">
{% block apply_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
        fill="none" stroke="{% block apply_icon_color %}#00bc8c{% endblock apply_icon_color %}" stroke-width="2" stroke-linecap="round"
        stroke-linejoin="round" class="feather feather-check">
    <polyline points="20 6 9 17 4 12"></polyline>
</svg>
{% endblock apply_img_icon %}
</button>

comment/templates/comment/comments/cancel_icon.html
<a class="js-comment-cancel {% block cancel_btn_cls %}btn btn-link{% endblock cancel_btn_cls %}" href="#">
{% block cancel_img_icon %}
<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block cancel_icon_color %}#E74C3C{% endblock cancel_icon_color %}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x">
    <line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line>
</svg>
{% endblock cancel_img_icon %}
</a>

comment/templates/comment/comments/comment_body.html
{% load comment_tags %}
<div class="row">
    {% if has_valid_profile %}
        <div class="{% block image_wrapper_cls %}col-2 col-md-1{% endblock image_wrapper_cls %}">
            <a href="{% get_profile_url comment %}">
                <img class="{% block image_cls %}w-100{% endblock image_cls %}"
                     src="{% get_img_path comment %}" alt="{% get_username_for_comment comment %}">
            </a>
        </div>
    {% endif %}
    {% include 'comment/comments/comment_content.html' with comment=comment %}
    {% if comment.user != user %}
        <div class="{% block three_dots_wrapper_cls %}col-1 position-relative d-flex justify-content-end{% endblock three_dots_wrapper_cls %}">
            {% include 'comment/comments/three_dots_menu.html' %}
        </div>
    {% endif %}
</div>

comment/templates/comment/comments/comment_content.html
{% load comment_tags %}
{% load i18n %}

{% if user.avatar %}
    <img class="img-rounded" src="{{ comment.user.avatar.url }}"
         style="width: 50px ;height: 50px ; border-radius: 30px"
         alt="بارگذاری نشد" data-lity>
{% endif %}
<div class=" media-comment-bubble.left-top media-comment-bubble js-updated-comment {% if comment.has_flagged_state %}flagged-comment {% endif %}{% block content_wrapper_cls %}{% if has_valid_profile %}col-9 col-md-10{% else %}co-11 mx-3{% endif %}{% endblock content_wrapper_cls %}"
     id="{{ comment.urlhash }}">
    {% block comment_content %}
        {% render_content comment %}
    {% endblock comment_content %}
    {% get_username_for_comment comment as username %}
    <div class="{% block footer_wrapper_cls %}mt-2 text-muted{% endblock footer_wrapper_cls %}">
        <small>
            <a style="    position: absolute;
    background: rgb(255,119,76);
    background: linear-gradient(45deg,rgb(255,119,76) 0%,rgb(255,78,76) 100%);
    color: #fff;
    padding: 1px 10px;
    border-radius: 5px;
    word-spacing: -2px;
    font-size: 17px;" class="{% block username_cls %}{% endblock username_cls %}" href="{% url 'account:profile_detail' comment.user.pk %}"
               title="View {{ comment.user }} profile">
                {% if comment.user.get_full_name %}
                    {{ comment.user.last_name }}
                {% else %}
                    {{ comment.user }}
                {% endif %}
                <br>
                </{% if comment.user %}a{% else %}span{% endif %}>
            <br>
                {% if comment.is_edited %}
                    <span class="font-italic"
                          title="{% trans 'Edited' %}">{% blocktrans with edited_time=comment.edited|timesince %}ویرایش
                        شده در : {{ edited_time }} قبل{% endblocktrans %}</span>
                {% else %}
                    <span class="font-italic"
                          title="{% trans 'Posted' %}">{% blocktrans with posted_time=comment.posted|timesince %}
                        {{ posted_time }} قبل{% endblocktrans %}</span>
                {% endif %}
                {% can_delete_comment comment user as can_delete %}
                {% if comment.user == user %}
                    | {% include 'comment/comments/edit_icon.html' %}
                    {% include 'comment/comments/delete_icon.html' %}
                {% elif can_delete %}
                    | {% include 'comment/comments/delete_icon.html' %}
                    {% if comment.is_flagged %}
                        {% include 'comment/comments/reject_icon.html' %}
                        {% if comment.is_edited %}
                            {% include 'comment/comments/resolve_icon.html' %}
                        {% endif %}
                    {% endif %}
                {% endif %}
                {% if user|can_block_users %}
                    {% include 'comment/block/block_icon.html' %}
                {% endif %}
                {% if comment.is_parent %}
                    {% get_replies_count comment user as reply_count %}
                    |
                    <span class="js-reply-number {% block reply_count_cls %}text-dark{% endblock reply_count_cls %}">{{ reply_count }}</span>
                    <a class="js-reply-link {% block reply_link_cls %}btn btn-link ml-1{% endblock reply_link_cls %}"
                       href="#">
                        {% blocktrans count reply_count=reply_count %} پاسخ{% plural %} پاسخ {% endblocktrans %}
                    </a>
                    {% if comment.user == user and is_subscription_allowed %}
                        <div class="{% block follow_icon_wrapper_cls %}d-inline ml-3{% endblock follow_icon_wrapper_cls %}">
                            {% include 'comment/follow/follow.html' with model_object=comment btnId=comment.id %}
                        </div>
                    {% endif %}
                {% endif %}
            </a>
        </small>

        {% include "comment/reactions/reactions.html" with comment=comment %}
    </div>
</div>

comment/templates/comment/comments/create_comment.html
{% load comment_tags %}
{% load i18n %}
{% if is_anonymous_allowed or user.is_authenticated %}


    <form class="js-comment-form" method="post" data-url="{% url 'comment:create' %}">
        {% csrf_token %}
        <div class="row">
            <div id="inputPlaceholder"
                 class="{% block text_area_wrapper_cls %}col-sm-9 col-md-10 px-2 m-2 m-sm-0{% endblock text_area_wrapper_cls %}">
                {% include 'comment/comments/comment_form.html' with placeholder=placeholder %}
            </div>
            <input name="model_name" value="{% get_model_name model_object %}" hidden>
            <input name="model_id" value="{{ model_object.id }}" hidden>
            <input name="app_name" value="{% get_app_name model_object %}" hidden>
            <input name="oauth" value="{{ oauth }}" hidden>
            {% if comment %}
                <input name="parent_id" value="{{ comment.id }}" type="hidden"/>
            {% endif %}
            <div id="buttonPlaceholder" class="col-sm-3 col-md-2 px-2 m-3 m-sm-0">

                <br>
                <button class="btn btn-shadow" {% if not comment %}onclick="history.go(0)"
                {% endif %}
                        type="submit" name="form_type" value="{% if comment %}child{% else %}parent{% endif %}"
                        data-email-required="{% if user.is_anonymous and is_anonymous_allowed %}true{% endif %}">
                    {% if comment %}{% trans "پاسخ" %}{% else %}{% trans "ارسال" %}{% endif %}
                </button>

            </div>
        </div>
    </form>
{% endif %}
{% if user.is_anonymous %}
    {% block login_info %}
        <div class="d-flex mb-3">
            {% if is_anonymous_allowed %}
                <p class="text-muted{% if comment %} h7{% endif %}">
                    {% trans "Comment Anonymously or" %}
                    <a class="text-success" href="{{ login_url }}?next={{ request.path }}">
                        <em>{% trans "ورود" %}</em>
                    </a>
                    {% trans "to keep your conversations intact" %}
                </p>
            {% else %}
                <p class="text-muted {% if comment %}h7{% endif %}">
                    <a class="text-success" href="{{ login_url }}?next={{ request.path }}">
                        <em>{% trans "ورود" %}</em>
                    </a>
                    {% trans "ارسال دیدگاه" %}
                </p>
            {% endif %}
            {% if oauth %}
                {% block oauth %}
                    <a class="mx-1 my-0 h4 github-color"
                       href="{% url 'social:begin' 'github' %}?next={{ request.path }}"><i
                            class="fa fa-github-square"></i></a>
                    <a class="mx-1 my-0 h4 facebook-color"
                       href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}"><i
                            class="fa fa-facebook-square"></i></a>
                    <a class="mx-1 my-0 h4 twitter-color"
                       href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}"><i
                            class="fa fa-twitter-square"></i></a>
                    <a class="mx-1 my-0 h4 google-color"
                       href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}"><i
                            class="fa fa-google-plus-square"></i></a>
                {% endblock oauth %}
            {% endif %}
        </div>
    {% endblock login_info %}
{% endif %}

comment/templates/comment/comments/messages.html
{% if messages %}
{% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

comment/templates/comment/comments/resolve_icon.html
{% load comment_tags %}
{% load i18n %}
<button title="{% if comment.has_resolved_state %}{% trans "Flag resolved" %}{% else %}{% trans "Resolve the flag" %}{% endif %}" class="js-flag-resolve {% block resolved_btn_cls %}btn btn-link{% endblock resolved_btn_cls %}" data-state="{{ comment.flag.RESOLVED }}" data-url="{% url 'comment:flag-change-state' pk=comment.id %}">

{% block resolved_img_icon %}
<svg class="{% if comment.has_resolved_state %}flag-resolved{% endif %}"
     xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
     fill="none" stroke="{% block resolved_icon_color %}#E74C3C{% endblock resolved_icon_color %}"
     stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">
     <path d="m11.939 20.395c-2.3228-3.8704-6.6445-2.2732-10.044-1.5539l0.10519-15.842h6c1.9144 0.42177 3.3887 1.4863 3.9187 3.1939"></path>
     <path d="m7.2106 9.7002 3.6287 5.1401 8.115-13.216" stroke-width="2.5"></path>
     <path d="m11.939 20.395c2.3228-3.8704 6.6445-2.2732 10.044-1.5539l-0.10519-15.841"></path>
</svg>
{% endblock resolved_img_icon %}
</button>

comment/templates/comment/comments/update_comment.html
{% load comment_tags %}
<div class="js-comment-update-mode col-10 col-md-11">
    <form class="js-comment-edit-form" method="post" data-url="{% url 'comment:edit' pk=comment.id %}">
        {% csrf_token %}
        {% include 'comment/comments/comment_form.html' with placeholder=placeholder %}
        <footer class="blockquote-footer edit-comment mt-2">
            <small>
                <input name="model_name" value="{% get_model_name model_object %}" hidden>
                <input name="model_id" value="{{ model_object.id }}" hidden>
                <input name="app_name" value="{% get_app_name model_object %}" hidden>
                <input name="oauth" value="{{oauth}}" hidden>

                {% include 'comment/comments/apply_icon.html' %}
                {% include 'comment/comments/cancel_icon.html' %}
            </small>
        </footer>
    </form>
</div>