config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from account.views import Register, activate, tracker
from two_factor.admin import AdminSiteOTPRequired
from two_factor.gateways.twilio.urls import urlpatterns as tf_twilio_urls
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("django.contrib.auth.urls")),
    path('shop/tracker/', tracker, name='Home'),
    path('account/', include('home.urls')),
    path('comment/', include('comment.urls')),
    path('account/', include("account.urls")),
    path('contact/', include("contact_list.urls")),
    path('', include(tf_twilio_urls)),
    path('client_list/', include("client_list.urls")),
    path('reference_list/', include("reference_list.urls")),
    path('shipment_list/', include("shipment_list.urls")),
    path('invoice/', include('invoice.urls')),
    path('mail/', include('mailbox2.urls')),
    path('todo/', include('todo.urls', namespace="todo")),
    path('calendar/', include('calendar_event.urls', namespace='calendar')),
    path('', include(tf_urls)),
    path('register/', Register.as_view(), name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('summernote/', include('django_summernote.urls')),
    path('tinymce/', include('tinymce.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home.views import Index

urlpatterns = [
    path('', Index, name='home')
]

todo/urls.py
from django.conf import settings
from django.urls import path

from todo import views
from todo.features import HAS_TASK_MERGE

app_name = "todo"

urlpatterns = [
    path("", views.list_lists, name="lists"),
    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path("reorder_tasks/", views.reorder_tasks, name="reorder_tasks"),
    # Allow users to post tasks from outside django-todo (e.g. for filing tickets - see docs)
    path("ticket/add/", views.external_add, name="external_add"),
    # Three paths into `list_detail` view
    path("mine/", views.list_detail, {"list_slug": "mine"}, name="mine"),
    path(
        "<int:list_id>/<str:list_slug>/completed/",
        views.list_detail,
        {"view_completed": True},
        name="list_detail_completed",
    ),
    path("<int:list_id>/<str:list_slug>/", views.list_detail, name="list_detail"),
    path("<int:list_id>/<str:list_slug>/delete/", views.del_list, name="del_list"),
    path("add_list/", views.add_list, name="add_list"),
    path("task/<int:task_id>/", views.task_detail, name="task_detail"),
    path(
        "attachment/remove/<int:attachment_id>/", views.remove_attachment, name="remove_attachment"
    ),
]

if HAS_TASK_MERGE:
    # ensure mail tracker autocomplete is optional
    from todo.views.task_autocomplete import TaskAutocomplete

    urlpatterns.append(
        path(
            "task/<int:task_id>/autocomplete/", TaskAutocomplete.as_view(), name="task_autocomplete"
        )
    )

urlpatterns.extend(
    [
        path("toggle_done/<int:task_id>/", views.toggle_done, name="task_toggle_done"),
        path("delete/<int:task_id>/", views.delete_task, name="delete_task"),
        path("search/", views.search, name="search"),
        path("import_csv/", views.import_csv, name="import_csv"),
    ]
)

todo/models.py
from __future__ import unicode_literals

import datetime
import os
import textwrap
from time import time

from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.contenttypes.fields import GenericRelation
from django.db import DEFAULT_DB_ALIAS, models
from django.db.transaction import Atomic, get_connection
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from comment.models import Comment


def get_attachment_upload_dir(instance, filename):
    """Determine upload dir for task attachment files.
    """

    return "/".join(["tasks", "attachments", str(instance.task.id), filename])


class LockedAtomicTransaction(Atomic):
    """
    modified from https://stackoverflow.com/a/41831049
    this is needed for safely merging

    Does a atomic transaction, but also locks the entire table for any transactions, for the duration of this
    transaction. Although this is the only way to avoid concurrency issues in certain situations, it should be used with
    caution, since it has impacts on performance, for obvious reasons...
    """

    def __init__(self, *models, using=None, savepoint=None):
        if using is None:
            using = DEFAULT_DB_ALIAS
        super().__init__(using, savepoint)
        self.models = models

    def __enter__(self):
        super(LockedAtomicTransaction, self).__enter__()

        # Make sure not to lock, when sqlite is used, or you'll run into problems while running tests!!!
        if settings.DATABASES[self.using]["ENGINE"] != "django.db.backends.sqlite3":
            cursor = None
            try:
                cursor = get_connection(self.using).cursor()
                for model in self.models:
                    cursor.execute(
                        "LOCK TABLE {table_name}".format(table_name=model._meta.db_table)
                    )
            finally:
                if cursor and not cursor.closed:
                    cursor.close()


class TaskList(models.Model):
    name = models.CharField(max_length=60)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        strtime = "".join(str(time()).split("."))
        string = "%s-%s" % (strtime[7:], self.group)
        self.slug = slugify(string)
        super(TaskList, self).save()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name = "لیست وظیفه"
        verbose_name_plural = "لیست وظایف"

        # Prevents (at the database level) creation of two lists with the same slug in the same group
        unique_together = ("group", "slug")


class Task(models.Model):
    title = models.CharField(max_length=140)
    task_list = models.ForeignKey(TaskList, on_delete=models.CASCADE, null=True)
    created_date = models.DateField(default=timezone.now, blank=True, null=True)
    due_date = models.DateField(blank=True, null=True)
    completed = models.BooleanField(default=False)
    completed_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        related_name="todo_created_by",
        on_delete=models.CASCADE,
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="todo_assigned_to",
        on_delete=models.CASCADE,
    )
    note = models.CharField(max_length=200,blank=True, null=True)
    priority = models.PositiveIntegerField(blank=True, null=True)

    # Has due date for an instance of this object passed?
    def overdue_status(self):
        "Returns whether the Tasks's due date has passed or not."
        if self.due_date and datetime.date.today() > self.due_date:
            return True

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("todo:task_detail", kwargs={"task_id": self.id})

    # Auto-set the Task creation / completed date
    def save(self, **kwargs):
        # If Task is being marked complete, set the completed_date
        if self.completed:
            self.completed_date = datetime.datetime.now()
        super(Task, self).save()

    def merge_into(self, merge_target):
        if merge_target.pk == self.pk:
            raise ValueError("can't merge a task with self")

        # lock the comments to avoid concurrent additions of comments after the
        # update request. these comments would be irremediably lost because of
        # the cascade clause
        with LockedAtomicTransaction(Comment):
            Comment.objects.filter(task=self).update(task=merge_target)
            self.delete()

    class Meta:
        ordering = ["priority", "created_date"]
        verbose_name = " وظیفه"
        verbose_name_plural = " وظایف"


class Comment(models.Model):
    """
    Not using Django's built-in comments because we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True
    )
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.datetime.now)
    email_from = models.CharField(max_length=320, blank=True, null=True)
    email_message_id = models.CharField(max_length=255, blank=True, null=True)

    body = models.TextField(blank=True)

    class Meta:
        # an email should only appear once per task
        unique_together = ("task", "email_message_id")
        verbose_name = " نظر"
        verbose_name_plural = " نظرات"

    @property
    def author_text(self):
        if self.author is not None:
            return str(self.author)

        assert self.email_message_id is not None
        return str(self.email_from)

    @property
    def snippet(self):
        body_snippet = textwrap.shorten(self.body, width=35, placeholder="...")
        # Define here rather than in __str__ so we can use it in the admin list_display
        return "{author} - {snippet}...".format(author=self.author_text, snippet=body_snippet)

    def __str__(self):
        return self.snippet


class Attachment(models.Model):
    """
    Defines a generic file attachment for use in M2M relation with Task.
    """

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    added_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=datetime.datetime.now)
    file = models.FileField(upload_to=get_attachment_upload_dir, max_length=255)

    def filename(self):
        return os.path.basename(self.file.name)

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension

    def __str__(self):
        return f"{self.task.id} - {self.file.name}"

    class Meta:

        verbose_name = " ضمیمه"
        verbose_name_plural = " ضمائم"

comment/views/base.py
from django.views.generic import FormView

from comment.conf import settings
from comment.context import DABContext
from comment.responses import DABResponseData
from comment.messages import EmailInfo
from comment.service.email import DABEmailService
from comment.forms import CommentForm


class BaseCommentView(FormView, DABResponseData):
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = context.pop('form')
        context.update(DABContext(self.request))
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


class CommentCreateMixin(BaseCommentView):
    email_service = None

    def _initialize_email_service(self, comment, request):
        self.email_service = DABEmailService(comment, request)

    def _send_notification_to_followers(self, comment, request):
        if settings.COMMENT_ALLOW_SUBSCRIPTION:
            self._initialize_email_service(comment, request)
            self.email_service.send_notification_to_followers()

    def perform_save(self, comment, request):
        comment.save()
        self._send_notification_to_followers(comment, request)
        comment.refresh_from_db()
        return comment

    def _handle_anonymous(self, comment, request, api=False):
        self._initialize_email_service(comment, request)
        self.email_service.send_confirmation_request(api=api)
        self.anonymous = True
        self.msg = EmailInfo.CONFIRMATION_SENT

    def perform_create(self, comment, request, api=False):
        if settings.COMMENT_ALLOW_ANONYMOUS and not comment.user:
            self._handle_anonymous(comment, request, api)
        else:
            comment = self.perform_save(comment, request)
        return comment

todo/views/add_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.text import slugify

from todo.forms import AddTaskListForm
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def add_list(request) -> HttpResponse:
    """Allow users to add a new todo list to the group they're in.
    """

    # Only staffers can add lists, regardless of TODO_STAFF_USER setting.
    if not request.user.is_staff:
        raise PermissionDenied

    if request.POST:
        form = AddTaskListForm(request.user, request.POST)
        if form.is_valid():
            try:
                newlist = form.save(commit=False)
                newlist.slug = slugify(newlist.name)
                newlist.save()
                messages.success(request, "یک لیست جدید اضافه شد.")
                return redirect("todo:lists")

            except IntegrityError:
                messages.warning(
                    request,
                    "یک مشکل در ذخیره کردن لیست جدید بوجود آمد. "
                    "به احتمال زیاد یک لیست با همان نام در همان گروه در حال حاضر وجود دارد.",
                )
    else:
        if request.user.groups.all().count() == 1:
            # FIXME: Assuming first of user's groups here; better to prompt for group
            form = AddTaskListForm(request.user, initial={"group": request.user.groups.all()[0]})
        else:
            form = AddTaskListForm(request.user)

    context = {"form": form}

    return render(request, "todo/add_list.html", context)

todo/views/del_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from todo.models import Task, TaskList
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def del_list(request, list_id: int, list_slug: str) -> HttpResponse:
    """Delete an entire list. Only staff members should be allowed to access this view.
    """
    task_list = get_object_or_404(TaskList, id=list_id)

    # Ensure user has permission to delete list. Get the group this list belongs to,
    # and check whether current user is a member of that group AND a staffer.
    if task_list.group not in request.user.groups.all():
        raise PermissionDenied    
    if not request.user.is_staff:
        raise PermissionDenied

    if request.method == "POST":
        TaskList.objects.get(id=task_list.id).delete()
        messages.success(request, "لیست {list_name} پاک شد.".format(list_name=task_list.name))
        return redirect("todo:lists")
    else:
        task_count_done = Task.objects.filter(task_list=task_list.id, completed=True).count()
        task_count_undone = Task.objects.filter(task_list=task_list.id, completed=False).count()
        task_count_total = Task.objects.filter(task_list=task_list.id).count()

    context = {
        "task_list": task_list,
        "task_count_done": task_count_done,
        "task_count_undone": task_count_undone,
        "task_count_total": task_count_total,
    }

    return render(request, "todo/del_list.html", context)

todo/views/delete_task.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from todo.models import Task
from todo.utils import staff_check


@login_required
@user_passes_test(staff_check)
def delete_task(request, task_id: int) -> HttpResponse:
    """Delete specified task.
    Redirect to the list from which the task came.
    """

    if request.method == "POST":
        task = get_object_or_404(Task, pk=task_id)

        redir_url = reverse(
            "todo:list_detail",
            kwargs={"list_id": task.task_list.id, "list_slug": task.task_list.slug},
        )

        # Permissions
        if not (
            (task.created_by == request.user)
            or (request.user.is_superuser)
            or (task.assigned_to == request.user)
            or (task.task_list.group in request.user.groups.all())
        ):
            raise PermissionDenied

        task.delete()

        messages.success(request, "کار '{}' پاک شد.".format(task.title))
        return redirect(redir_url)

    else:
        raise PermissionDenied

todo/templates/todo/add_list.html
{% extends "todo/base.html" %}
{% load widget_tweaks %}
{% block page_heading %}{% endblock %}
{% block title %}افزودن لیست انجام کار {% endblock %}
{% block content %}

    <!-- title and breadcrumb -->
    <div class="page-header">
        <h2 class="page-title">اضافه کردن لیست</h2>
        <ol class="breadcrumb">
            <li><a href="index.html">پیشخوان</a></li>
            <li><span>لیست ها</span></li>
            <li><span>افزودن لیست</span></li>
        </ol>

        <div class="Jalali pull-right">
            <p id="JalaliDayAndDate"></p>
        </div>
    </div>
    <!-- /End title and breadcrumb -->
    <table id="content_table">
        <tr class="row1">
            <td id="column0" class="connectcolumn" colspan="2">

                <!-- Inline forms -->
                <div class="panel" id="color">
                    <div class="panel-heading">
                        <i class="la la-hashtag sort-hand"></i>
                        فرم های خطی
                        <div class="pan-btn expand min"></div>
                    </div>
                    <div class="panel-body">
                        <form action="" method="post">
                            <div class="form-group label-floating">
                                {% csrf_token %}

                                <div class="form-group label-floating">
                                    <label for="id_name">نام لیست</label>
                                    <input aria-describedby="inputNameHelp" class="form-control" id="id_name"
                                           name="name" placeholder=""
                                           type="text">

                                </div>
                                <br>
                                <div class="input-group">
                                    <label class="control-label">گروه</label><br>
                                    {{ form.group|add_class:'form-control' }}
                                </div>
                                <div class="form-group col-md-6 mb-0">
                                    {{ form.slug }}
                                </div>
                                <button class="btn btn-primary" type="submit">ثبت</button>
                            </div>

                        </form>
                    </div>
                </div>
                <!-- /End Inline forms -->
            </td>
        </tr>
    </table>
{% endblock %}

todo/templates/todo/base.html
{% extends "base.html" %}
{% load static %}

{% block extrahead %}
	<link rel="stylesheet" type="text/css" href="{% static 'todo/css/styles.css' %}" />
{% endblock extrahead %}

todo/templates/todo/import_csv.html
{% extends "todo/base.html" %}
{% load static %}

{% block title %}Import CSV{% endblock %}

{% block content %}
  <h2>
    وارد کردن فایل CSV
  </h2>

  <p>
    Batch-import tasks by uploading a specifically-formatted CSV.
    See documentation for formatting rules.
    Successs and failures will be reported here.
  </p>

  {% if results %}
    <div class="card mb-4">
      <div class="card-header">
        نتیجه آپلود فایل CSV
      </div>
      <div class="card-body">

        {% if results.summaries %}
          <p>
            <b>خلاصه:</b>
          </p>
          <ul>
            {% for line in results.summaries %}
              <li>{{ line }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        {% if results.upserts %}
          <p>
            <b>Upserts (tasks created or updated):</b>
          </p>
          <ul>
            {% for line in results.upserts %}
              <li>{{ line }}</li>
            {% endfor %}
          </ul>
        {% endif %}

        {% if results.errors %}
          <p>
            <b>Errors (tasks NOT created or updated):</b>
          </p>
          <ul>
            {% for error_row in results.errors %}
              {% for k, error_list in error_row.items  %}
                <li>CSV row {{ k }}</li>
                <ul>
                  {% for err in error_list %}
                    <li>{{ err }}</li>
                  {% endfor %}
                </ul>
              {% endfor %}
            {% endfor %}
          </ul>
        {% endif %}


      </div>
    </div>
  {% endif %}

  <div class="card">
    <div class="card-header">
      Upload Tasks
    </div>
    <div class="card-body">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
          <input type="file" name="csvfile" accept="text/csv">
        </div>
        <button type="submit" class="btn btn-primary mt-4">Upload</button>
      </form>
    </div>
  </div>

{% endblock %}

todo/templates/todo/list_detail.html
{% extends "todo/base.html" %}
{% load static %}

{% block title %}Todo List: {{ task_list.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h2 class="page-title">اضافه کردن لیست</h2>
        <ol class="breadcrumb">
            <li><a href="index.html">پیشخوان</a></li>
            <li><span>لیست ها</span></li>
            <li><span>افزودن لیست</span></li>
        </ol>

        <div class="Jalali pull-right">
            <p id="JalaliDayAndDate"></p>
        </div>
    </div>
    <!-- /End title and breadcrumb -->
    <table id="content_table">
        <tr class="row1">
            <td id="column0" class="connectcolumn" colspan="2">

                <!-- Inline forms -->
                <div class="panel" id="color">
                    <div class="panel-heading">
                        <i class="la la-hashtag sort-hand"></i>
                        فرم های خطی
                        <div class="pan-btn expand min"></div>
                    </div>
                    <div class="panel-body">
                        {% if list_slug != "mine" %}
                            <button class="btn btn-primary" id="AddTaskButton" type="button"
                                    data-toggle="collapse" data-target="#AddEditTask">اضافه کردن برنامه کاری
                            </button>

                            {# Task edit / new task form #}
                            <div id="AddEditTask" class="collapse">
                                {% include 'todo/include/task_edit.html' %}
                            </div>
                            <hr/>
                        {% endif %}

                        {% if tasks %}
                            {% if list_slug == "mine" %}
                                <h1> برنامه های کاری مختص به من ( در همه لیست ها) </h1>
                            {% else %}
                                <h1>{{ view_completed|yesno:"کارهای به پایان رسیده, کارها" }} در
                                    "{{ task_list.name }}"</h1>
                                <p><small><i>در گروه کاری "{{ task_list.group }}" - وظایف را جهت اولویت بندی جابجا
                                    کنید.</i></small></p>
                            {% endif %}

                            <table class="table" id="tasktable">
                                <tr class="nodrop">
                                    <th>کارها</th>
                                    <th>زمان ایجاد</th>
                                    <th>زمان انجام کار</th>
                                    <th>ایجاد کننده</th>
                                    <th>انجام دهنده</th>
                                    <th>علامت گذاری</th>
                                </tr>

                                {% for task in tasks %}
                                    <tr id="{{ task.id }}">
                                        <td>
                                            <a href="{% url 'todo:task_detail' task.id %}">{{ task.title|truncatewords:10 }}</a>
                                        </td>
                                        <td>
                                            {{ task.created_date|date:"m/d/Y" }}
                                        </td>
                                        <td>
              <span {% if task.overdue_status %}class="overdue"{% endif %}>
                {{ task.due_date|date:"m/d/Y" }}
              </span>
                                        </td>
                                        <td>
                                            {{ task.created_by }}
                                        </td>
                                        <td>
                                            {% if task.assigned_to %}{{ task.assigned_to }}{% else %}هرکسی{% endif %}
                                        </td>
                                        <td>
                                            <form method="post" action="{% url "todo:task_toggle_done" task.id %}"
                                                  role="form">
                                                {% csrf_token %}
                                                <button class="btn btn-info btn-sm" type="submit" name="toggle_done">
                                                    {% if view_completed %}
                                                        انجام نشده
                                                    {% else %}
                                                        انجام شده
                                                    {% endif %}
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>

                            {% include 'todo/include/toggle_delete.html' %}

                        {% else %}
                            <h4>هیچ کاری جهت انجام در این لیست وجود ندارد . </h4>
                            {% include 'todo/include/toggle_delete.html' %}

                        {% endif %}
                    </div>
                </div>
                <!-- /End Inline forms -->
            </td>
        </tr>
    </table>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'todo/js/jquery.tablednd_0_5.js' %}" type="text/javascript"></script>

    <script type="text/javascript">
        function order_tasks(data) {
            // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
            // data in a list. We pass that list as an object ("data") to a Django view
            // to save new priorities on each task in the list.
            $.post("{% url 'todo:reorder_tasks' %}", data, "json");
            return false;
        };

        $(document).ready(function () {
            // Initialise the task table for drag/drop re-ordering
            $("#tasktable").tableDnD();

            $('#tasktable').tableDnD({
                onDrop: function (table, row) {
                    order_tasks($.tableDnD.serialize());
                }
            });

        });

        // When adding a task, change the text of the Add Task button
        function handleClick() {
            console.log(this.innerHTML);
            this.innerHTML = (this.innerHTML == '' ? 'کنسل' : 'افزودن وظیفه');
        }

        document.getElementById('AddTaskButton').onclick = handleClick;
    </script>
{% endblock extra_js %}

todo/templates/todo/list_lists.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }}لیست های موجود {% endblock %}

{% block content %}
    <!-- title and breadcrumb -->
    <div class="page-header">
        <h2 class="page-title">اضافه کردن لیست</h2>
        <ol class="breadcrumb">
            <li><a href="index.html">پیشخوان</a></li>
            <li><span>لیست ها</span></li>
            <li><span>افزودن لیست</span></li>
        </ol>

        <div class="Jalali pull-right">
            <p id="JalaliDayAndDate"></p>
        </div>
    </div>
    <!-- /End title and breadcrumb -->
    <table id="content_table">
        <tr class="row1">
            <td id="column0" class="connectcolumn" colspan="2">

                <!-- Inline forms -->
                <div class="panel" id="color">
                    <div class="panel-heading">
                        <i class="la la-hashtag sort-hand"></i>
                        فرم های خطی
                        <div class="pan-btn expand min"></div>
                    </div>
                    <div class="panel-body">
                        <h1>لیست های کاری</h1>

                        <p>مجموع کارهای پیش رو :<span style="color: red">{{ task_count }}</span> تعداد لیست ها :<span
                                style="color: red">{{ list_count }}</span></p>

                        {% regroup lists by group as section_list %}
                        {% for group in section_list %}
                            <h3>'نام گروه': {{ group.grouper }}</h3>
                            <ul class="list-group mb-4">
                                {% for task in group.list %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center">
                                        <a href="{% url 'todo:list_detail' task.id task.slug %}">{{ task.name }}</a>
                                        <span class="badge badge-primary badge-pill">{{ task.task_set.count }}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endfor %}

                        <div class="mt-3">

                            {% if user.is_staff %}
                                <a href="{% url 'todo:add_list' %}" class="btn btn-primary">افزودن یک لیست جدید کار</a>
                            {% else %}
                                <a href="" class="btn btn-primary disabled">If you were staff, you could create a new
                                    list</a>
                            {% endif %}

                        </div>

                    </div>
                </div>
                <!-- /End Inline forms -->
            </td>
        </tr>
    </table>
{% endblock %}